[package]
name = "tobaru"
version = "0.2.0"
edition = "2018"

[features]
default = ["tls-rustls"]
tls-native = ["openssl", "tokio-native-tls", "native-tls"]
tls-rustls = ["rustls", "tokio-rustls", "webpki"]

[dependencies]
async-trait = "*"
env_logger = "*"
futures-util = "*"
ipnet = "*"
json = "*"
log = "*"
native-tls = { version = "*", optional = true }
openssl = { version = "*", optional = true }
rustls = { version = "*", features = ["dangerous_configuration"], optional = true }
tokio = { version = "*", features = ["io-util", "macros", "net", "rt-multi-thread"] }
tokio-native-tls = { version = "*", optional = true }
tokio-rustls = { version = "*", features = ["dangerous_configuration"], optional = true }
treebitmap = "*"
webpki = { version = "0.21.4", optional = true }

[profile.release]
opt-level = 3
lto = true
