[package]
name = "tobaru"
version = "0.4.0"
edition = "2021"

[features]
default = ["tls-rustls"]
tls-native = ["openssl", "tokio-native-tls", "native-tls"]
tls-rustls = ["rustls", "rustls-pemfile", "tokio-rustls", "webpki-roots"]

[dependencies]
async-trait = "*"
env_logger = "*"
futures-util = "*"
ipnet = "*"
json = "*"
log = "*"
native-tls = { version = "*", optional = true }
openssl = { version = "*", optional = true }
rustls = { version = "*", features = ["dangerous_configuration"], optional = true }
rustls-pemfile = { version = "*", optional = true }
tokio = { version = "*", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-native-tls = { version = "*", optional = true }
tokio-rustls = { version = "*", features = ["dangerous_configuration"], optional = true }
treebitmap = "*"
webpki-roots = { version = "*", optional = true }

[profile.release]
opt-level = 3
lto = true
