[package]
name = "tobaru"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "Port forwarding CLI utility written in Rust with allowlists, TLS, iptables support, round-robin forwarding (load balancing), and IP-to-destination mapping."
homepage = "https://github.com/cfal/tobaru/"
repository = "https://github.com/cfal/tobaru/"
readme = "README.md"
keywords = ["tunnel", "proxy", "tcp", "forward", "port"]
categories = ["command-line-utilities", "network-programming"]

[features]
default = ["tls-rustls"]
tls-native = ["openssl", "tokio-native-tls", "native-tls"]
tls-rustls = ["rustls", "rustls-pemfile", "tokio-rustls", "webpki-roots"]

[dependencies]
async-trait = "0.1.52"
env_logger = "0.9.0"
futures-util = "0.3.18"
ipnet = "2.3.1"
json = "0.12.4"
log = "0.4.14"
native-tls = { version = "0.2.8", optional = true }
openssl = { version = "0.10.38", optional = true }
rustls = { version = "0.20.2", features = ["dangerous_configuration"], optional = true }
rustls-pemfile = { version = "0.2.1", optional = true }
tokio = { version = "1.14.0", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-native-tls = { version = "0.3.0", optional = true }
tokio-rustls = { version = "0.23.1", features = ["dangerous_configuration"], optional = true }
treebitmap = "0.4.0"
webpki-roots = { version = "0.22.1", optional = true }

[profile.release]
opt-level = 3
lto = true
