[package]
name = "tobaru"
version = "0.7.0"
edition = "2021"
license = "MIT"
description = "Port forwarding CLI utility written in Rust with allowlists, TLS SNI and ALPN routing, round-robin forwarding (load balancing), IP-to-destination mapping, and iptables support."
homepage = "https://github.com/cfal/tobaru/"
repository = "https://github.com/cfal/tobaru/"
readme = "README.md"
keywords = ["tunnel", "proxy", "tcp", "forward", "port"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
async-trait = "*"
env_logger = "*"
futures = "*"
ipnet = "*"
json = "*"
log = "*"
parking_lot = "*"
percent-encoding = "*"
rustls = { version = "*", features = ["dangerous_configuration"] }
rustls-pemfile = { version = "*" }
tokio = { version = "*", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { version = "*", features = ["dangerous_configuration"] }
treebitmap = "*"
url = "*"
webpki-roots = { version = "*" }
notify = ">=5.0.0-pre.13"

[profile.release]
opt-level = 3
lto = "fat"
